# Generated by Django 4.0.2 on 2022-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
