# Generated by Django 4.0.2 on 2022-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comm',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
