# Generated by Django 4.0.2 on 2022-04-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_post_comm_post_likes'),
        ('social_network', '0008_remove_post_text_alter_post_caption'),
    ]

    operations = [
    ]
