# Generated by Django 4.0.3 on 2022-04-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
