# Generated by Django 4.0.3 on 2022-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0013_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comm',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
