# Generated by Django 4.0.3 on 2022-04-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0016_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
