# Generated by Django 4.0.3 on 2022-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_alter_profile_options_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
