# Generated by Django 4.0.3 on 2022-05-02 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Приватный'),
        ),
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.TextField(default='lobby', verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
